# Generated by Django 6.0.1 on 2026-04-17 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0005_alter_documentoaluno_options_and_more'),
        ('turmas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConselhoClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resumo_geral', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.turma')),
            ],
        ),
        migrations.CreateModel(
            name='ConselhoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FloatField(blank=True, null=True)),
                ('frequencia', models.FloatField(blank=True, null=True)),
                ('total_ocorrencias', models.IntegerField(default=0)),
                ('classificacao', models.CharField(max_length=20)),
                ('diagnostico', models.TextField()),
                ('prioridade', models.CharField(max_length=20)),
                ('sugestao', models.TextField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
                ('conselho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='conselho.conselhoclasse')),
            ],
        ),
    ]
