# Generated by Django 6.0.1 on 2026-04-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_alter_documentoaluno_options_and_more'),
        ('conselho', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conselhoaluno',
            options={'ordering': ['aluno']},
        ),
        migrations.AlterModelOptions(
            name='conselhoclasse',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AddField(
            model_name='conselhoaluno',
            name='apa',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3),
        ),
        migrations.AddField(
            model_name='conselhoaluno',
            name='aprendizagem',
            field=models.CharField(blank=True, choices=[('ok', 'Acompanha'), ('nao', 'Não faz atividades')], max_length=20),
        ),
        migrations.AddField(
            model_name='conselhoaluno',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='conselhoaluno',
            name='chamar_familia',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3),
        ),
        migrations.AddField(
            model_name='conselhoaluno',
            name='disciplina',
            field=models.CharField(blank=True, choices=[('ind', 'Indisciplinado'), ('reg', 'Regular')], max_length=20),
        ),
        migrations.AddField(
            model_name='conselhoaluno',
            name='faltas',
            field=models.CharField(blank=True, choices=[('freq', 'Frequente'), ('faltoso', 'Faltoso'), ('gravida', 'Grávida'), ('atestado', 'Atestado')], max_length=20),
        ),
        migrations.AddField(
            model_name='conselhoaluno',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conselhoaluno',
            name='reclassificacao',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3),
        ),
        migrations.AddField(
            model_name='conselhoclasse',
            name='data_conselho',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conselhoclasse',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('finalizado', 'Finalizado')], default='rascunho', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='conselhoaluno',
            unique_together={('conselho', 'aluno')},
        ),
    ]
