# Generated by Django 6.0.1 on 2026-07-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conselho', '0002_alter_conselhoaluno_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conselhoaluno',
            name='afastamento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3),
        ),
        migrations.AddField(
            model_name='conselhoaluno',
            name='busca_ativa',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3),
        ),
        migrations.AddField(
            model_name='conselhoaluno',
            name='plano_recomposicao',
            field=models.CharField(blank=True, choices=[('feito', 'Feito'), ('nao_feito', 'Não feito')], max_length=15),
        ),
    ]
