# Generated by Django 6.0.1 on 2026-02-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do aluno')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('data_matricula', models.DateField(help_text='Data manual, pode ser retroativa', verbose_name='Data da matrícula')),
                ('turma_ano_letivo', models.IntegerField(blank=True, null=True, verbose_name='Ano letivo da matrícula')),
                ('turma_etapa', models.CharField(blank=True, max_length=30, null=True, verbose_name='Etapa')),
                ('turma_ano_escolar', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ano/Série')),
                ('turma_nome', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nome da turma')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=150, null=True)),
                ('nome_mae', models.CharField(max_length=150)),
                ('telefone_responsavel', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_telefone_responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone_responsavel2', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_telefone_responsavel2', models.CharField(blank=True, max_length=100, null=True)),
                ('possui_dependencia', models.BooleanField(default=False, verbose_name='Aluno com dependência')),
                ('aluno_trabalhador', models.BooleanField(default=False, verbose_name='Aluno trabalhador / estagiário / menor aprendiz')),
                ('aluno_paed', models.BooleanField(default=False)),
                ('observacao_paed', models.TextField(blank=True, null=True)),
                ('aluno_busca_ativa', models.BooleanField(default=False)),
                ('numero_ficai', models.CharField(blank=True, max_length=50, null=True)),
                ('recomposicao', models.BooleanField(default=False)),
                ('transferido', models.BooleanField(default=False)),
                ('data_transferencia', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['matricula'],
            },
        ),
    ]
