# Generated by Django 6.0.1 on 2026-03-13 02:39

import alunos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=alunos.models.foto_aluno_path, verbose_name='Foto do aluno'),
        ),
        migrations.CreateModel(
            name='DocumentoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=alunos.models.caminho_laudo, verbose_name='Arquivo do laudo')),
                ('tipo_laudo', models.CharField(max_length=150, verbose_name='Tipo de laudo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição / detalhes do laudo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Documento do aluno',
                'verbose_name_plural': 'Documentos dos alunos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
