# Generated by Django 6.0.1 on 2026-03-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_aluno_foto_documentoaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto_thumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='alunos/thumbs/'),
        ),
    ]
