# Generated by Django 6.0.1 on 2026-03-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_aluno_foto_thumb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoaluno',
            options={'ordering': ['-data_laudo'], 'verbose_name': 'Documento do aluno', 'verbose_name_plural': 'Documentos dos alunos'},
        ),
        migrations.AddField(
            model_name='documentoaluno',
            name='data_laudo',
            field=models.DateField(blank=True, null=True, verbose_name='Data do laudo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='aluno_trabalhador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='possui_dependencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma_ano_escolar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma_ano_letivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma_etapa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma_nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documentoaluno',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação do laudo'),
        ),
    ]
