# Generated by Django 6.0.1 on 2026-07-02 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_alter_documentoaluno_options_and_more'),
        ('turmas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='historico',
            field=models.TextField(blank=True, help_text='Registro de movimentações, transferências e observações.', null=True, verbose_name='Histórico do aluno'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='reclassificado',
            field=models.BooleanField(default=False, verbose_name='Aluno reclassificado'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='situacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Situação Escolar'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_transferencia',
            field=models.DateField(blank=True, null=True, verbose_name='Data da transferência'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='transferido',
            field=models.BooleanField(default=False, verbose_name='Aluno transferido'),
        ),
        migrations.CreateModel(
            name='HistoricoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MATRICULA', 'Matrícula'), ('TRANSFERENCIA_TURMA', 'Transferência de Turma'), ('TRANSFERENCIA_ESCOLA', 'Transferência de Escola'), ('RECLASSIFICACAO', 'Reclassificação'), ('REMANEJAMENTO', 'Remanejamento'), ('CANCELAMENTO', 'Cancelamento')], max_length=30)),
                ('data', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='alunos.aluno')),
                ('turma_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='turmas.turma')),
                ('turma_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='turmas.turma')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data'],
            },
        ),
    ]
