# Generated by Django 6.0.1 on 2026-02-24 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('frequencia', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='turmas.turma'),
        ),
        migrations.AddField(
            model_name='frequenciaaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno'),
        ),
        migrations.AddField(
            model_name='frequenciaaluno',
            name='frequencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='frequencia.frequencia'),
        ),
        migrations.AlterUniqueTogether(
            name='frequencia',
            unique_together={('turma', 'data')},
        ),
        migrations.AlterUniqueTogether(
            name='frequenciaaluno',
            unique_together={('frequencia', 'aluno')},
        ),
    ]
