# Generated by Django 6.0.1 on 2026-02-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('perfis_permitidos', models.JSONField(default=list, help_text="Ex: ['ADMIN','COORD','PROF']")),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
