# Generated by Django 6.0.1 on 2026-02-24 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('tipo_ocorrencia', models.CharField(choices=[('DISC', 'Disciplinar'), ('ATRA', 'Atraso'), ('UNIF', 'Uniforme'), ('OUT', 'Outros')], max_length=10)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('RESOLVIDA', 'Resolvida'), ('ANDAMENTO', 'Em andamento')], default='ABERTA', max_length=15)),
                ('descricao', models.TextField()),
                ('providencias', models.TextField(blank=True)),
                ('data', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ficai', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nº FICAI')),
                ('ficai_aberta', models.BooleanField(default=False)),
                ('ficai_numero', models.CharField(blank=True, max_length=30, null=True)),
                ('ficai_data', models.DateField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='alunos.aluno')),
            ],
        ),
    ]
