# Generated by Django 6.0.1 on 2026-04-29 18:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('TURMA', 'Troca de turma'), ('ESCOLA', 'Transferência de escola'), ('INTERNA', 'Dentro da escola'), ('INTERESTADUAL', 'Fora do estado')], max_length=20)),
                ('escola_origem', models.CharField(max_length=255)),
                ('escola_destino', models.CharField(blank=True, max_length=255, null=True)),
                ('data_lancamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('prazo_limite', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em análise'), ('CONCLUIDA', 'Concluída'), ('ATRASADA', 'Atrasada')], default='ABERTA', max_length=20)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_criadas', to=settings.AUTH_USER_MODEL)),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_resolvidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
