# Generated by Django 6.0.1 on 2026-02-24 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.IntegerField()),
                ('etapa', models.CharField(choices=[('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio'), ('EJA', 'EJA'), ('TEC', 'Ensino Técnico')], max_length=10)),
                ('ano_escolar', models.CharField(default='99º', help_text='Ex: 6º Ano, 3º Ano EM', max_length=20, verbose_name='Ano Escolar')),
                ('nome', models.CharField(default='AA', help_text='Ex: A, B, C, ALFA, BETA', max_length=20, verbose_name='Nome da Turma')),
                ('turno', models.CharField(choices=[('MAT', 'Matutino'), ('VES', 'Vespertino'), ('NOT', 'Noturno'), ('INT', 'Integral')], default='MAT', max_length=10, verbose_name='Turno')),
                ('max_alunos', models.PositiveIntegerField(default=35, verbose_name='Máximo de Alunos')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno_lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lider_de_turma', to='alunos.aluno')),
            ],
            options={
                'ordering': ['-ano_letivo', 'etapa'],
            },
        ),
    ]
